version: "3.5"

services:
  backend:
    build: ./docker/backend
    container_name: arxiview-backend
    ports:
    - "80:3000"
    tty: true
    restart: unless-stopped
    depends_on:
    - mongodb
    volumes:
    - ./backend:/usr/src/app
    - $UPLOADS_PATH:/uploads
  mongodb:
    image: mongo:latest
    container_name: arxiview-mongo
    tty: true
    restart: unless-stopped
    volumes:
    - $MONGODB_DATA_PATH:/data/db
