version: "3.5"

services:
  backend:
    build: ./docker/backend
    container_name: arxiview-backend
    ports:
    - "80:3000"
    tty: true
    restart: unless-stopped
    depends_on:
    - mongodb
    volumes:
    - ./backend:/usr/src/app
    - $UPLOADS_PATH:/uploads
  mongodb:
    image: mongo:latest
    container_name: arxiview-mongo
    tty: true
    restart: unless-stopped
    volumes:
    - $MONGODB_DATA_PATH:/data/db
  compiler:
    build: ./docker/compiler
    container_name: arxiview-compiler
    hostname: arxiview-compiler
    volumes:
      - $UPLOADS_PATH:/home/workspace
    ports:
      - "5000:5000"
    restart: unless-stopped
    tty: true
    #network_mode: "host"
